### ISSUE TITLE
Normalizing spectrograms

### ISSUE THREAD

**Issue by stolpa4** [f90/AdversarialAudioSeparation#5]
As far as I know, the result of log1p(x) can be negative. You use this function to 'normalize' the spectrograms of target accompaniment and vocals and then use the difference between network outputs and these spectrograms in your loss function. However, network outputs after ReLU can't be negative. 
I see the paper and I realize that it must work, so what do I miss? Please help me

**Comment by f90** [comment]
In general yes, log1p(x) can be negative, and then we would have problems. But in our case, x is the magnitude (energy) of the spectrogram at a given time and frequency, which is always at least 0. Therefore log(x+1) >= log(1) = 0, and the result is also always at least 0.
This allows us to use a ReLU function for the generator output.

**Comment by stolpa4** [comment]
Thank you so much for the answer!
